spring:
  profiles:
    active:
      - dev
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      default-page-size: 10
      max-page-size: 100
backend:
  upload-path: assets
---
spring:
  profiles: prod
backend:
  upload-path: assets-prod
---
spring:
  profiles: dev
backend:
  upload-path: assets-dev